version: "3.8"
services:
  webapp:
    image: tcdmv/webapp:1.0.7
    ports:
      - 8081:8080
  postgres:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD:my-pwd
